name: PHPUnit Tests

on:
  push:
    branches:
      - dev

jobs:
  test-php:
    runs-on: ubuntu-latest
    name: PHPUnit
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Start WP-ENV
        run: pnpm wp-env start

      - name: Install Composer
        run: pnpm composer install

      - name: Run Tests
        run: pnpm phpunit

